export const authConstants={

    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS'

}

export const categoryConstants={

    GET_ALL_CATEGORY_REQUESTS:'GET_ALL_CATEGORY_REQUESTS',
    GET_ALL_CATEGORY_SUCCESS:'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE:'GET_ALL_CATEGORY_FAILURE'

}